### PR TITLE
Updated to require workers 0.0.19.

### PR DESCRIPTION
**Pull request by spigaz**
I updated to require the latest worker 0.0.19 otherwise I get dependencies conflicts.

### CODE REVIEW

**Comment by logankeenan** [comment]
@spigaz - Thanks so much for you contribution! I'll be able to merge and cut a release tonight sometime after 8:00 PM central time. I noticed there was another release of worker-rs. I'll make an additional release for that too.

**Comment by spigaz** [comment]
You are right, there you go...

I added the test runner to the cargo config, so now you can run cargo test once you install the test runner.

Added some cleaning to some errors you were having...

**Comment by logankeenan** [comment]
@spigaz 

I've released version 0.8.0 with your changes. Thanks so much for your contribution!
https://crates.io/crates/axum-cloudflare-adapter/0.8.0

**Comment by spigaz** [comment]
No problem, glad to help!

**Pull request merged**
