### PR TITLE
Updated to workers 0.0.24.

### PR DESCRIPTION
**Pull request by spigaz**
Is there a way to avoid having to update everytime?

Its just that releases are going to get common and this adapter is going to continue to be relevant in the near future.

Thanks!

### CODE REVIEW

**Comment by avsaase** [comment]
> Is there a way to avoid having to update everytime?

I think not. Cargo doesn't consider any `0.0.x` version to be compatible.

**Comment by spigaz** [comment]
Thanks @avsaase! I thought so.

**Comment by avsaase** [comment]
I wouldn't hold my breath waiting for that. The best course of action is to quickly migrate to use the `http` types in the `worker` crate so you don't need the adapter anymore.

**Comment by spigaz** [comment]
The adapter's relevance is to allow incremental migration and in that sense, I don't know how much legacy code is in the older model.

What will end up happening is a drop of the older model.

**Comment by avsaase** [comment]
0.0.24 was just released: https://github.com/cloudflare/workers-rs/releases/tag/v0.0.24

This gets a little hard to keep up with.

**Comment by spigaz** [comment]
@avsaase Do you have a suggestion?

Its not a blocker, as you can always create a fork and reference it in cargo easily.

I'm not the overhead this implies to @logankeenan to make a release.

**Comment by logankeenan** [comment]
@spigaz - I'll look into getting dependabot setup so the upgrades can be automated and a GH action tasks for publishing.

**Comment by spigaz** [comment]
@logankeenan Thanks! I apologise for this, because workers now is gaining pace and so far this is still the best path to migrate to the http version.

**Pull request merged**
