### PR TITLE
Updated to the latest workers-rs 0.1.0

### PR DESCRIPTION
**Pull request by spigaz**
Hi hopefully this will stick for some time. :)

Thanks!

### CODE REVIEW

**Comment by spigaz** [comment]
@logankeenan Did you receive the notification? Thanks! Sorry!

**Comment by logankeenan** [comment]
> @logankeenan Did you receive the notification? Thanks! Sorry!

I got that notification 😄

[0.11.0](https://crates.io/crates/axum-cloudflare-adapter/0.11.0) has been released. Thank you for the contribution and reminder!

**Comment by spigaz** [comment]
Thanks @logankeenan!

You inspired us on this path... You got relevant for us! Thanks!

Right now I expect that when 0.1.x comes out we won't need to bother you. 

But for 0.x...

**Comment by logankeenan** [comment]
> Right now I expect that when 0.1.x comes out we won't need to bother you.

@spigaz 
It's not a bother at all. I'm just happy people have found this crate helpful. I really appreciate you keeping it up-to-date !

**Pull request merged**
